//! Cross-implementation known-answer test (KAT) for the control-plane Noise_IK
//! handshake transcript.
//!
//! `ts_control_noise::Handshake::initialize` drives a `noise_protocol` IK handshake
//! over `<X25519, ChaCha20Poly1305BigEndian, Blake2s>` (noise-rust-crypto) — the exact
//! construction Tailscale's `control/controlbase` uses on the wire: protocol name
//! `Noise_IK_25519_ChaChaPoly_BLAKE2s`, both handshake payloads EMPTY, and the client
//! (initiator) takes `tx = c1 (i->r)` / `rx = c2 (r->i)` from `Split()`.
//!
//! Only the AEAD leaf (the big-endian transport nonce) was previously Go-pinned
//! (`be_aead_matches_go_kat` in `cipher.rs`). The IK TRANSCRIPT itself — the DH
//! schedule, the MixHash/MixKey ordering, prologue absorption, and the `Split` ->
//! `(tx, rx)` DIRECTION — was not. A divergence there would let two Rust nodes
//! interoperate while silently failing against every Go control server: a total
//! registration break invisible to a self-round-trip test. The most dangerous variant
//! is a `tx`/`rx` swap — it passes a Rust-vs-Rust round-trip (both sides swapped agree)
//! yet breaks real registration, where one party is Go.
//!
//! Provenance: the reference bytes come from an INDEPENDENT Go Noise implementation
//! (`github.com/flynn/noise` v1.1.0, primitives from `golang.org/x/crypto` v0.52.0)
//! driven with FIXED static + ephemeral keypairs, generated by
//! `tests/vectors/gen/control_noise/main.go` and recorded in
//! `tests/vectors/control_noise_ik_transcript.json`. The vectors are embedded inline
//! below (mirroring `blake2s_kat` / `be_aead_matches_go_kat` / the WG handshake KAT,
//! which likewise inline their reference values).
//!
//! The KAT pins the transcript MECHANICS with a FIXED prologue constant
//! (`PROLOGUE_ASCII` below). That is deliberately independent of the production
//! `CapabilityVersion::CURRENT` wiring — the prologue string is whatever the caller
//! passes to `Handshake::initialize`; this KAT hardcodes one fixed value, byte-identical
//! to the generator, so the transcript is reproducible.
//!
//! These tests drive the REAL production builder path (`noise_protocol`'s
//! `HandshakeStateBuilder` configured exactly as `Handshake::initialize` does) with a
//! test-only fixed-ephemeral seam (`builder.set_e`), so what is pinned is the production
//! code's transcript, not a parallel re-implementation.

use noise_protocol::{
    Cipher as _, CipherState, DH, HandshakeState, HandshakeStateBuilder, patterns::noise_ik,
};
use noise_rust_crypto::{Blake2s, X25519, sensitive::Sensitive};
use ts_control_noise::ChaCha20Poly1305BigEndian;
use zeroize::Zeroizing;

type Cipher = ChaCha20Poly1305BigEndian;

// ----- Reference vector (from tests/vectors/control_noise_ik_transcript.json) -----

/// Fixed prologue. MUST match the generator byte-for-byte. NOT the production
/// `CapabilityVersion::CURRENT` prologue — a fixed test constant pinning the mechanics.
const PROLOGUE_ASCII: &str = "Tailscale Control Protocol v109";

const INIT_STATIC_PRIV: &str = "0101010101010101010101010101010101010101010101010101010101010101";
const INIT_STATIC_PUB: &str = "a4e09292b651c278b9772c569f5fa9bb13d906b46ab68c9df9dc2b4409f8a209";
const RESP_STATIC_PRIV: &str = "0202020202020202020202020202020202020202020202020202020202020202";
const RESP_STATIC_PUB: &str = "ce8d3ad1ccb633ec7b70c17814a5c76ecd029685050d344745ba05870e587d59";
const INIT_EPHEM_PRIV: &str = "0303030303030303030303030303030303030303030303030303030303030303";
const INIT_EPHEM_PUB: &str = "5dfedd3b6bd47f6fa28ee15d969d5bb0ea53774d488bdaf9df1c6e0124b3ef22";
const RESP_EPHEM_PRIV: &str = "0404040404040404040404040404040404040404040404040404040404040404";
const RESP_EPHEM_PUB: &str = "ac01b2209e86354fb853237b5de0f4fab13c7fcbf433a61c019369617fecf10b";

/// Noise IK msg1 body (initiator -> responder, empty payload). This is exactly the
/// 96-byte `Initiation::PAYLOAD_LEN` blob `write_message(&[], &mut [0u8; 96])` produces;
/// Go's msg1 carries no `controlbase` framing header, so the raw Noise body is compared.
const MSG1_HEX: &str = "5dfedd3b6bd47f6fa28ee15d969d5bb0ea53774d488bdaf9df1c6e0124b3ef224391bcfef3f1b0f051873c2103356110f8056ef928c4354783347c74dc7b71b745b99ea89a2aca15a0393bb6ae570a1fcd6a61036e3b5681526d01585d5c52bf";
/// Noise IK msg2 body (responder -> initiator, empty payload).
const MSG2_HEX: &str = "ac01b2209e86354fb853237b5de0f4fab13c7fcbf433a61c019369617fecf10bed19a2c480c9b718cd8af4020b0154b7";

/// Probe plaintext sealed under each split cipher at counter 0 (empty AD).
const PROBE_ASCII: &str = "control-noise-probe";
/// Go `csI0.Encrypt` of the probe = initiator send = i->r = the initiator's `tx` cipher.
const TX_PROBE_SEALED_HEX: &str =
    "75900508cbf6b97737f3ecde187ac64c8e6901ee7e514cf29af708c3bdb75335cc4a6e";
/// Go `csI1.Encrypt` of the probe = initiator recv = r->i = the initiator's `rx` cipher.
const RX_PROBE_SEALED_HEX: &str =
    "19d2652f5998c738c1cd1038d4635d0ed39148f761e48a8f5d1224cc0aa5d0cd594bc9";

const HANDSHAKE_HASH_HEX: &str = "444c0e5610855da6fcc5feb9ba12daad9f452d802ca40628249b2fba7286ee1c";

// ----- helpers -----

fn unhex(s: &str) -> Vec<u8> {
    assert!(
        s.len().is_multiple_of(2),
        "hex string must have even length"
    );
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[i * 2..i * 2 + 2], 16).expect("valid hex byte"))
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        s.push_str(&format!("{b:02x}"));
    }
    s
}

fn key32(s: &str) -> [u8; 32] {
    unhex(s).try_into().expect("32-byte key")
}

/// Build the noise-rust-crypto X25519 private-key type exactly as `Handshake::initialize`
/// does for the static key (`Sensitive::from(Zeroizing::from(bytes))`).
fn sensitive_key(bytes: [u8; 32]) -> Sensitive<[u8; 32]> {
    Sensitive::from(Zeroizing::from(bytes))
}

/// Construct the initiator handshake state EXACTLY as `Handshake::initialize` does
/// (`noise_ik`, `is_initiator = true`, `set_rs(resp_static_pub)`, `set_prologue(...)`,
/// `set_s(init_static_priv)`), PLUS the test-only fixed ephemeral seam `set_e`.
fn build_initiator() -> HandshakeState<X25519, Cipher, Blake2s> {
    let prologue = PROLOGUE_ASCII.as_bytes();
    let mut builder = HandshakeStateBuilder::<X25519>::new();
    builder.set_pattern(noise_ik());
    builder.set_is_initiator(true);
    builder.set_rs(key32(RESP_STATIC_PUB));
    builder.set_prologue(prologue);
    builder.set_s(sensitive_key(key32(INIT_STATIC_PRIV)));
    builder.set_e(sensitive_key(key32(INIT_EPHEM_PRIV)));
    builder.build_handshake_state()
}

/// Construct the responder handshake state the way the real control server would: IK
/// responder does NOT pre-set `rs` (it learns the initiator static from the encrypted
/// `s` token inside msg1). Fixed static + fixed ephemeral injected.
fn build_responder() -> HandshakeState<X25519, Cipher, Blake2s> {
    let prologue = PROLOGUE_ASCII.as_bytes();
    let mut builder = HandshakeStateBuilder::<X25519>::new();
    builder.set_pattern(noise_ik());
    builder.set_is_initiator(false);
    builder.set_prologue(prologue);
    builder.set_s(sensitive_key(key32(RESP_STATIC_PRIV)));
    builder.set_e(sensitive_key(key32(RESP_EPHEM_PRIV)));
    builder.build_handshake_state()
}

/// Seal `pt` under a freshly-`Split` `CipherState` at counter 0, empty AD. counter 0 is
/// identical under little-endian (Go flynn/noise) and big-endian (the fork's transport
/// AEAD) nonce packing, so this is a valid cross-implementation check.
fn seal_at_zero(cs: &mut CipherState<Cipher>, pt: &[u8]) -> Vec<u8> {
    cs.encrypt_vec(pt)
}

// ----- tests -----

/// The full Go-pinned transcript: build the REAL production initiator (with fixed
/// ephemeral), assert msg1 byte-for-byte, feed Go's msg2, then assert the split ciphers
/// match Go's — INCLUDING DIRECTION (`tx` = i->r, `rx` = r->i). The direction assertion
/// is the load-bearing one: a `tx`/`rx` swap survives a round-trip but breaks real
/// registration against a Go peer.
#[test]
fn noise_ik_transcript_matches_go_kat() {
    // Sanity: the construction name is the Tailscale control protocol name. The fork's
    // cipher reports "ChaChaPoly", matching flynn/noise's cipher name component.
    assert_eq!(
        Cipher::name(),
        "ChaChaPoly",
        "cipher name component of the Noise protocol name diverged"
    );

    let mut state = build_initiator();

    // msg1: write_message with an EMPTY payload, into a fixed-size 96-byte buffer (the
    // production `Initiation::PAYLOAD_LEN`). Compare the raw Noise body to Go's msg1.
    let mut msg1 = [0u8; 96];
    state
        .write_message(&[], &mut msg1)
        .expect("initiation write_message must fit PAYLOAD_LEN");
    assert_eq!(
        hex(&msg1),
        MSG1_HEX,
        "Noise IK msg1 body diverges from the Go reference (DH schedule / MixHash / \
         prologue absorption mismatch)"
    );

    // msg2: read Go's responder message. Must yield an EMPTY payload and complete.
    let payload = state
        .read_message_vec(&unhex(MSG2_HEX))
        .expect("must read Go's msg2");
    assert!(payload.is_empty(), "msg2 payload must be empty");
    assert!(state.completed(), "handshake must be completed after msg2");

    // Split. noise_protocol returns `(tx, rx)` in Noise spec order for the initiator:
    // tx = c1 = initiator->responder, rx = c2 = responder->initiator.
    let (mut tx, mut rx) = state.get_ciphers();

    let probe = PROBE_ASCII.as_bytes();

    // THE LOAD-BEARING DIRECTION ASSERTIONS.
    let tx_sealed = seal_at_zero(&mut tx, probe);
    assert_eq!(
        hex(&tx_sealed),
        TX_PROBE_SEALED_HEX,
        "tx must be the initiator->responder cipher (Go csI0). A mismatch here means the \
         split-key derivation or the tx/rx DIRECTION diverges from Go — a tx/rx swap \
         passes a round-trip but breaks real control registration."
    );
    let rx_sealed = seal_at_zero(&mut rx, probe);
    assert_eq!(
        hex(&rx_sealed),
        RX_PROBE_SEALED_HEX,
        "rx must be the responder->initiator cipher (Go csI1)"
    );
}

/// Guard that the fixed inputs really are the ones Go generated the vectors from: the
/// X25519 base-point public keys derived from the fixed private scalars must match Go's
/// emitted public keys. (Also documents the handshake-hash pin for cross-reference.)
#[test]
fn fixed_public_keys_match_go() {
    let cases = [
        (INIT_STATIC_PRIV, INIT_STATIC_PUB, "init static"),
        (RESP_STATIC_PRIV, RESP_STATIC_PUB, "resp static"),
        (INIT_EPHEM_PRIV, INIT_EPHEM_PUB, "init ephemeral"),
        (RESP_EPHEM_PRIV, RESP_EPHEM_PUB, "resp ephemeral"),
    ];
    for (priv_hex, pub_hex, label) in cases {
        // Derive via the exact production X25519 DH path (noise-rust-crypto), not a
        // separate dalek dependency: this is the same code the real handshake uses.
        let pk = <X25519 as DH>::pubkey(&sensitive_key(key32(priv_hex)));
        assert_eq!(
            hex(&pk),
            pub_hex,
            "{label} X25519 base-point public key must match the Go vector"
        );
    }
    // Document that the handshake-hash constant is a fixed 32-byte value (channel binding).
    assert_eq!(
        unhex(HANDSHAKE_HASH_HEX).len(),
        32,
        "handshake hash must be 32 bytes (BLAKE2s-256)"
    );
}

/// Rust-vs-Rust self-consistency (Option B supplement): run the full IK transcript with
/// fixed ephemerals on BOTH sides entirely in Rust, then assert the two parties derive
/// matching, correctly-directioned split ciphers — the initiator's `tx` (i->r) is opened
/// by the responder's first cipher, and the responder's i->r cipher round-trips to the
/// initiator's `rx`. This guards the wiring even without the Go toolchain, and
/// independently re-derives the direction the Go KAT pins.
#[test]
fn noise_ik_transcript_rust_self_consistent() {
    let mut initiator = build_initiator();
    let mut responder = build_responder();

    // msg1 i->r.
    let mut msg1 = [0u8; 96];
    initiator
        .write_message(&[], &mut msg1)
        .expect("initiator msg1");
    let r_payload = responder
        .read_message_vec(&msg1)
        .expect("responder reads msg1");
    assert!(r_payload.is_empty(), "msg1 payload empty");

    // msg2 r->i.
    let msg2 = responder.write_message_vec(&[]).expect("responder msg2");
    let i_payload = initiator
        .read_message_vec(&msg2)
        .expect("initiator reads msg2");
    assert!(i_payload.is_empty(), "msg2 payload empty");

    assert!(
        initiator.completed() && responder.completed(),
        "both completed"
    );

    // Both parties split. Spec order on each side is (i->r, r->i).
    let (mut i_tx, mut i_rx) = initiator.get_ciphers(); // (i->r, r->i)
    let (mut r_tx, mut r_rx) = responder.get_ciphers(); // (i->r, r->i)

    // The two implementations must agree on the IK transcript: identical raw msg bytes
    // here AND below the matching split-cipher directions.
    assert_eq!(
        hex(&msg1),
        MSG1_HEX,
        "Rust-vs-Rust msg1 must equal the pinned Go msg1"
    );

    let probe = PROBE_ASCII.as_bytes();

    // Initiator's tx (i->r) must be opened by the responder's RECEIVE cipher for i->r,
    // which on the responder is its first split cipher (also labeled i->r). Seal with the
    // initiator's tx, open with the responder's i->r cipher.
    let tx_sealed = i_tx.encrypt_vec(probe);
    let opened = r_tx
        .decrypt_vec(&tx_sealed)
        .expect("responder i->r cipher must open initiator tx");
    assert_eq!(opened, probe, "i->r round-trip plaintext mismatch");

    // Symmetrically, responder's r->i cipher seals to the initiator's rx.
    let rx_sealed = r_rx.encrypt_vec(probe);
    let opened2 = i_rx
        .decrypt_vec(&rx_sealed)
        .expect("initiator rx cipher must open responder r->i");
    assert_eq!(opened2, probe, "r->i round-trip plaintext mismatch");
}
